language: python
python: '2.7'
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- easy_install -U setuptools
- wget https://bootstrap.pypa.io/bootstrap-buildout.py
- python bootstrap-buildout.py -c travis.cfg
- ./bin/buildout -N -t 3 -c travis.cfg
script: ./bin/test
