language: python
python: '2.7'
install:
- mkdir -p buildout-cache/eggs
- mkdir -p buildout-cache/downloads
- pip install setuptools zc.buildout
- sudo apt-get install swig xmlsec1
- ./bin/buildout -N -t 3 -c travis.cfg
script: ./bin/test
