name: hl.pas.samlplugin CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install System Packages
        run: |
          sudo apt-get -y install swig xmlsec1
      - name: pip install
        run: pip install zc.buildout==3.0.1
      - name: buildout
        run: buildout -N -t 10 -c ci.cfg
      - name: Run tests
        run: bin/test --all
